session_name: fastapi_serviceutils
start_directory: "${PWD}"
shell_command_before: source "$VIRTUAL_ENV/bin/activate"
environment:
    PYTHONPATH: ${PWD}
    SHELL: /usr/bin/zsh
    EDITOR: /opt/nvim/nvim.appimage
windows:
    - window_name: development
      layout: main-vertical
      options:
          main-pane-width: 100
      panes:
          - focus: true
          - shell_command:
              - make update
          - shell_command:
              - pytest --looponfail
