version: '3'

services:
  testdb:
    image: postgres:11.2-alpine
    ports:
      - "5434:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=monitordb
